### ISSUE TITLE
Uploading .png or .jpeg image files doesn't work

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/scooter#93] opened 2014-09-03 11:14 UTC
If you upload a .png or a .jpeg image file using the editor then a file is created on github but it seems to be corrupted - on the staging site it gives a broken link and looking at the version downloaded through SourceTree it won't open using any image editor. However if a file is pushed using SourceTree rather than uploaded via the editor it works fine.

The first two tabs at the top of https://staging.isaacphysics.org/why_physics show images successfully uploaded using SourceTree, while the third tab shows one uploaded using the editor.

**Comment by daviesian** [comment] 2015-02-11 11:19
Duplicate of #87.

**Closed by daviesian** 2015-02-11 11:19 UTC
Labels: bug
