### ISSUE TITLE
Concept look up not working?

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/scooter#89] opened 2014-08-25 12:06 UTC
Issue found in 2c1bc70baa3a046d19db4bf8326c8d8e096b3ca9

Network connection at home isn't brilliant but the concepts are not appearing for me as I type in the metadata box.

**Comment by daviesian** [comment] 2015-02-11 11:18
This was a bug. Fixed in 622ce2a2efc01a3d49f2ca2abd011bec58598dbe.

**Comment by nh357** [comment] 2015-02-12 11:35
Can no longer add related content again. Again it worked last week, but has stopped working today on both Safari and Chrome. Trying to add it to cavendish_experiment under: questions -> physics - >fields -> gravitational -> level 5

**Comment by daviesian** [comment] 2015-02-12 11:37
Duplicate of #103 .

**Closed by daviesian** 2015-02-12 11:37 UTC
Labels: bug
