### ISSUE TITLE
cannot add related content

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/scooter#105] opened 2015-01-13 10:42 UTC
Issue found in 3aa3355b83e800980c602cfab5f1548b15f81d0f

We can no longer easily add related content to questions or concepts using the metadata box. You can still add it using the son, but it is time consuming.

**Comment by daviesian** [comment] 2015-02-11 11:11
Duplicate of #89.

**Closed by daviesian** 2015-02-11 11:11 UTC
