### ISSUE TITLE
Cannot upload figures

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/scooter#104] opened 2015-01-13 10:41 UTC
Issue found in 3aa3355b83e800980c602cfab5f1548b15f81d0f

We can no longer upload figures on the editor by clicking the image and choosing a new file. It doesn't seem to upload the figure to github.

**Comment by daviesian** [comment] 2015-02-11 11:44
Duplicate of #87.

**Closed by daviesian** 2015-02-11 11:44 UTC
